# Generated by Django 5.2.4 on 2025-07-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recibe_notificaciones',
            field=models.BooleanField(default=False),
        ),
    ]
