# Generated by Django 2.2.1 on 2019-06-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Seleccione el último día del mes', verbose_name='mes')),
                ('padron', models.PositiveIntegerField(verbose_name='Padrón Electoral')),
                ('lista', models.PositiveIntegerField(verbose_name='Lista Nominal')),
                ('diferencia', models.IntegerField(verbose_name='Diferencia')),
                ('cob', models.FloatField(verbose_name='Cobertura')),
            ],
        ),
    ]
