# Generated by Django 2.2.1 on 2019-06-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobertura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobertura',
            name='cob',
            field=models.FloatField(editable=False, verbose_name='Cobertura'),
        ),
        migrations.AlterField(
            model_name='cobertura',
            name='diferencia',
            field=models.IntegerField(editable=False, verbose_name='Diferencia'),
        ),
    ]
