# Generated by Django 5.2.4 on 2025-10-22 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaqueteEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Nombre del archivo original, ej: 290151A_20251015_093000.json.gz', max_length=100, unique=True)),
                ('file_hash', models.CharField(help_text='Hash SHA-256 del contenido del archivo para asegurar unicidad.', max_length=64, unique=True)),
                ('mac', models.CharField(help_text='MAC extraída del nombre del archivo.', max_length=6)),
                ('device_id', models.CharField(help_text='ID del dispositivo extraído del nombre del archivo.', max_length=1)),
                ('record_count', models.PositiveIntegerField(default=0, help_text='Número de encuestas contenidas en este archivo.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se subió el archivo al sistema.')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.PositiveSmallIntegerField(default=29, editable=False)),
                ('distrito', models.PositiveSmallIntegerField(editable=False)),
                ('mac', models.CharField(editable=False, max_length=6)),
                ('device_id', models.CharField(max_length=8)),
                ('p0_tipo_visita', models.PositiveSmallIntegerField()),
                ('p1_claridad_info', models.PositiveSmallIntegerField()),
                ('p2_amabilidad', models.PositiveSmallIntegerField()),
                ('p3_instalaciones', models.PositiveSmallIntegerField()),
                ('p4_tiempo_espera', models.PositiveSmallIntegerField()),
                ('is_exported', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(help_text='Fecha y hora de la encuesta en el dispositivo')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='vozmac.paqueteencuesta')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
