# Generated by Django 5.2.4 on 2025-10-13 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vozmac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaqueteEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Nombre del archivo original, ej: 290151A_20251015_093000.json.gz', max_length=100, unique=True)),
                ('file_hash', models.CharField(help_text='Hash SHA-256 del contenido del archivo para asegurar unicidad.', max_length=64, unique=True)),
                ('mac', models.CharField(max_length=6, unique=True)),
                ('device_id', models.CharField(help_text='ID del dispositivo extraído del nombre del archivo.', max_length=1)),
                ('record_count', models.PositiveIntegerField(default=0, help_text='Número de encuestas contenidas en este archivo.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se subió el archivo al sistema.')),
            ],
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='batch',
        ),
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(help_text='Fecha y hora de la encuesta en el dispositivo')),
                ('p1_tipo', models.BooleanField()),
                ('p2_informacion', models.PositiveSmallIntegerField()),
                ('p3_servicio', models.PositiveSmallIntegerField()),
                ('p4_instalaciones', models.PositiveSmallIntegerField()),
                ('p5_tiempo', models.PositiveSmallIntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='vozmac.paqueteencuesta')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SurveyBatch',
        ),
        migrations.DeleteModel(
            name='SurveyResponse',
        ),
    ]
