# Generated by Django 5.2.4 on 2025-10-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vozmac', '0002_paqueteencuesta_remove_surveyresponse_batch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuestaencuesta',
            old_name='p2_informacion',
            new_name='p0_tipo_visita',
        ),
        migrations.RenameField(
            model_name='respuestaencuesta',
            old_name='p3_servicio',
            new_name='p1_claridad_info',
        ),
        migrations.RenameField(
            model_name='respuestaencuesta',
            old_name='p4_instalaciones',
            new_name='p2_amabilidad',
        ),
        migrations.RenameField(
            model_name='respuestaencuesta',
            old_name='p5_tiempo',
            new_name='p3_instalaciones',
        ),
        migrations.RemoveField(
            model_name='respuestaencuesta',
            name='p1_tipo',
        ),
        migrations.AddField(
            model_name='respuestaencuesta',
            name='p4_tiempo_espera',
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
    ]
