# Generated by Django 5.2.4 on 2025-10-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vozmac', '0003_rename_p2_informacion_respuestaencuesta_p0_tipo_visita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paqueteencuesta',
            name='mac',
            field=models.CharField(help_text='MAC extraída del nombre del archivo.', max_length=6),
        ),
    ]
