# Generated by Django 5.2.4 on 2025-10-21 19:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vozmac', '0004_alter_paqueteencuesta_mac'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaencuesta',
            name='device_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuestaencuesta',
            name='distrito',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuestaencuesta',
            name='entidad',
            field=models.PositiveSmallIntegerField(default=29, editable=False),
        ),
        migrations.AddField(
            model_name='respuestaencuesta',
            name='is_exported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='respuestaencuesta',
            name='mac',
            field=models.CharField(default=123456, editable=False, max_length=6),
            preserve_default=False,
        ),
    ]
