# Generated by Django 2.1.7 on 2019-03-11 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_final', models.DateTimeField()),
                ('all_day', models.BooleanField(verbose_name='Todo el día')),
                ('remesa', models.CharField(editable=False, max_length=7, null=True, verbose_name='Remesa')),
                ('inhabilitado', models.BooleanField()),
                ('caso_cau', models.CharField(max_length=15)),
                ('descripcion', models.TextField()),
                ('solucion', models.TextField()),
                ('duracion', models.DurationField(editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.PositiveSmallIntegerField(editable=False, verbose_name='Distrito')),
                ('mac', models.CharField(max_length=6, verbose_name='Módulo')),
                ('doble_turno', models.BooleanField()),
                ('sabados', models.BooleanField()),
                ('configuracion', models.PositiveSmallIntegerField(choices=[(1, 'Básico'), (2, 'Básico + 1'), (3, 'Básico + 2'), (4, 'Básico + 3'), (5, 'Básico + 4'), (6, 'Básico + 5'), (7, 'Básico + 6')], verbose_name='Configuración')),
                ('horas', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='incidencia',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.Modulo'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.Tipo'),
        ),
    ]
