# Generated by Django 2.1.3 on 2019-02-13 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('distrito', models.PositiveSmallIntegerField()),
                ('modulo', models.CharField(max_length=6)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('remesa', models.CharField(editable=False, max_length=7, null=True, verbose_name='Remesa')),
                ('inhabilitado', models.BooleanField()),
                ('caso_cau', models.CharField(max_length=15)),
                ('descripcion', models.TextField()),
                ('solucion', models.TextField()),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='incidencia',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.Tipo'),
        ),
    ]
