# Generated by Django 2.1.3 on 2019-02-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='distrito',
            field=models.PositiveSmallIntegerField(editable=False, verbose_name='Distrito'),
        ),
    ]
