# Generated by Django 2.1.7 on 2019-03-11 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_modulo_tipo_mac'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulo',
            old_name='horas',
            new_name='dias',
        ),
    ]
