# Generated by Django 2.1.3 on 2019-02-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_auto_20190213_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='duracion',
            field=models.DurationField(editable=False, null=True),
        ),
    ]
