# Generated by Django 2.1.7 on 2019-03-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0003_auto_20190311_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='fecha_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='solucion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
