# Generated by Django 2.1.3 on 2019-02-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0003_incidencia_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='fecha_final',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='modulo',
            field=models.CharField(choices=[('290151', '290151'), ('290152', '290152'), ('290153', '290153'), ('290251', '290251'), ('290252', '290252'), ('290253', '290253'), ('290254', '290254'), ('290351', '290351'), ('290352', '290352'), ('290353', '290353')], max_length=6),
        ),
    ]
