# Generated by Django 2.1.7 on 2019-03-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0005_auto_20190307_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.PositiveSmallIntegerField()),
                ('mac', models.CharField(max_length=6, verbose_name='Módulo')),
                ('doble_turno', models.BooleanField()),
                ('sabados', models.BooleanField()),
                ('horas', models.PositiveIntegerField()),
            ],
        ),
    ]
