# Generated by Django 3.0.4 on 2020-04-07 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0002_auto_20200407_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_role', to='metas.Role', verbose_name='Puesto'),
        ),
    ]
