# Generated by Django 3.0.4 on 2020-04-06 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0002_puesto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Puesto',
            new_name='Rol',
        ),
    ]
