# Generated by Django 2.0.5 on 2018-05-24 00:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0003_auto_20180522_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='jmm01',
            name='campos',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
