# Generated by Django 3.0.4 on 2020-04-10 17:47

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metas', '0003_auto_20200407_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='proof',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Campos'),
        ),
        migrations.AlterField(
            model_name='proof',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_goal', to='metas.Goal', verbose_name='Meta'),
        ),
        migrations.AlterField(
            model_name='proof',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='proof_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
