# Generated by Django 3.0.4 on 2020-04-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0003_auto_20200406_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
