# Generated by Django 2.0.5 on 2018-05-24 00:55

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metas', '0004_jmm01_campos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('eval_calidad', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Evaluación del Criterio de Calidad')),
                ('eval_oportunidad', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Evaluación del Criterio de Oportunidad')),
                ('campos', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidenciaFK_meta', to='metas.MetasSPE')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidenciaFK_pipol', to=settings.AUTH_USER_MODEL, verbose_name='Miembro del SPE')),
                ('usuario', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='evidenciaFK_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
            },
        ),
        migrations.RemoveField(
            model_name='jmm01',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='jmm01',
            name='miembro',
        ),
        migrations.RemoveField(
            model_name='jmm01',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='JMM01',
        ),
    ]
