# Generated by Django 3.0.4 on 2020-04-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0004_auto_20200406_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='description',
            field=models.CharField(max_length=75),
        ),
    ]
