# Generated by Django 3.0.4 on 2020-04-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0005_auto_20200406_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='description',
            field=models.CharField(max_length=75, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='Orden'),
        ),
    ]
