# Generated by Django 3.2.5 on 2021-07-24 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0005_auto_20201126_1552'),
        ('metas', '0005_auto_20210723_1946'),
    ]

    operations = [
    ]
