# Generated by Django 3.0.4 on 2020-04-06 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0006_auto_20200406_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=4, verbose_name='Sitio')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('mail', models.CharField(max_length=50, verbose_name='Correo Electrónico')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_rol', to='metas.Rol')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_site', to='metas.Site')),
            ],
        ),
    ]
