# Generated by Django 3.0.4 on 2020-04-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0007_member_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre'),
        ),
    ]
