# Generated by Django 3.2.9 on 2021-11-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='scope',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Proceso'), (1, 'Actividad'), (2, 'Sistema'), (3, 'Formato'), (4, 'Indicador'), (5, 'Objetivo')], default=0, verbose_name='Alcance'),
        ),
    ]
