# Generated by Django 3.2.9 on 2021-11-26 18:06

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_auto_20211124_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='slug',
            field=models.SlugField(default='', max_length=200, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='results',
            field=tinymce.models.HTMLField(blank=True, help_text='Escribe los resultados que has obtenido con tu proyecto', null=True, verbose_name='Resultados'),
        ),
    ]
