# Generated by Django 3.2.9 on 2021-11-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_auto_20211126_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
