# Generated by Django 5.0.6 on 2024-08-27 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_alter_idea_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='contact',
            field=models.CharField(help_text='Escribe tu correo electrónico institucional', max_length=100, verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='scope',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Proceso'), (1, 'Actividad'), (2, 'Sistema'), (3, 'Formato'), (4, 'Indicador'), (5, 'Objetivo'), (6, 'Cuadro de Mando')], default=0, help_text='Selecciona que vas a afectar con tu idea', verbose_name='Alcance'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(help_text='Ponle un nombre a tu idea o proyecto', max_length=200, verbose_name='Título'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('viable', models.BooleanField(default=False, verbose_name='Viable')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.idea')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
