# Generated by Django 5.0.6 on 2024-08-27 19:17

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0008_resolve_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolve',
            name='resolve',
            field=tinymce.models.HTMLField(help_text='Describe la resolución de la idea', verbose_name='Resolución'),
        ),
    ]
