# Generated by Django 5.2.4 on 2026-01-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0011_idea_created_resolve_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resolve',
            options={'ordering': ('-created',)},
        ),
    ]
