# Generated by Django 2.0.5 on 2018-06-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='lugar',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Barra: Área de Trámite/Entrega'), (2, 'Mesa: Mesa de atención')], verbose_name='Lugar de atención'),
        ),
    ]
