# Generated by Django 2.1 on 2018-08-20 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='creacion',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='actualiza',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='revision',
            old_name='creacion',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='revision',
            old_name='actualiza',
            new_name='updated',
        ),
    ]
