# Generated by Django 3.2.5 on 2021-07-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20180820_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='aprobado',
            field=models.BooleanField(default=False, verbose_name='Documento en aprobación'),
        ),
    ]
