# Generated by Django 4.2.3 on 2023-07-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_documento_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='lmc',
            field=models.BooleanField(default=False, verbose_name='Pertenece a la Lista Maestra de Documentos'),
        ),
    ]
