# Generated by Django 4.2.3 on 2023-07-24 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_documento_lmc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='lmc',
            new_name='lmd',
        ),
    ]
