# Generated by Django 4.2.3 on 2023-07-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_rename_lmc_documento_lmd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='lmd',
            field=models.BooleanField(default=False, help_text='Pertenece a la Lista Maestra de Documentos', verbose_name='LMD'),
        ),
    ]
