# Generated by Django 4.2.4 on 2023-08-24 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docs', '0007_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='resolucion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='resuelto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reporte',
            name='resuelto_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='resuelto_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='causa',
            field=models.CharField(choices=[('1', 'No se puede descargar el documento '), ('2', 'El proceso asignado no es correcto'), ('3', 'Hay una nueva versión del documento'), ('4', 'Otro problema')], max_length=1),
        ),
    ]
