# Generated by Django 4.2.6 on 2023-10-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_reporte_resolucion_reporte_resuelto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='causa',
            field=models.CharField(choices=[('1', 'No se puede descargar el documento '), ('2', 'El proceso asignado no es correcto'), ('3', 'Hay una nueva versión del documento'), ('4', 'Documento faltante'), ('99', 'Otro problema')], max_length=2),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='resolucion',
            field=models.TextField(blank=True, verbose_name='Resolución'),
        ),
    ]
