# Generated by Django 5.2.4 on 2025-07-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_alter_reporte_causa_alter_reporte_resolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='fecha_notificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='notificacion_enviada',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('S', 'Semanal'), ('U', 'Urgente')], max_length=1)),
                ('asunto', models.CharField(max_length=255)),
                ('cuerpo_html', models.TextField()),
                ('destinatarios', models.TextField()),
                ('revisiones', models.ManyToManyField(to='docs.revision')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
            },
        ),
    ]
