# Generated by Django 5.2.4 on 2025-07-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0010_revision_fecha_notificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='notificacion_urgente',
            field=models.BooleanField(default=False),
        ),
    ]
