# Generated by Django 5.2.4 on 2025-07-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0012_remove_notificacion_destinatarios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='destinatario',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='destinatarios',
            field=models.TextField(blank=True),
        ),
    ]
