# Generated by Django 5.2.4 on 2025-07-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0013_remove_notificacion_destinatario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='resultados',
            field=models.BooleanField(default=False, help_text='Documento que contiene resultados del SGC', verbose_name='Resultados'),
        ),
    ]
