# Generated by Django 5.2.4 on 2026-01-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0014_documento_resultados'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='checksum',
            field=models.CharField(blank=True, editable=False, help_text='Checksum SHA-256 del archivo asociado a la revisión', max_length=64),
        ),
    ]
