# Generated by Django 5.2.4 on 2026-01-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0015_revision_checksum'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='checksum_algoritmo',
            field=models.CharField(default='sha256', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='revision',
            name='checksum_calculado_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='checksum_verificado_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
