# Generated by Django 2.0.5 on 2018-05-23 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import metas.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetasSPE',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('puesto', models.CharField(choices=[('VEL', 'Vocal Ejecutivo de Junta Local'), ('VSL', 'Vocal Secretario de Junta Local'), ('VRL', 'Vocal del RFE de Junta Local'), ('VCL', 'Vocal de Capacitación de Junta Local'), ('VOL', 'Vocal de Organización de Junta Local'), ('VED', 'Vocal Ejecutivo de Junta Distrital'), ('VSD', 'Vocal Secretario de Junta Distrital'), ('VRD', 'Vocal del RFE de Junta Distrital'), ('VCD', 'Vocal de Capacitación de Junta Distrital'), ('VOD', 'Vocal de Organización de Junta Distrital'), ('JOSA', 'JOSA'), ('JOSAD', 'JOSAD'), ('JMM', 'Jefe de Monitoreo a Módulos'), ('JOCE', 'Jefe de Cartografía'), ('RA', 'Rama Administrativa')], max_length=6, verbose_name='Cargo')),
                ('clave', models.CharField(max_length=2, verbose_name='Clave de la Meta')),
                ('nom_corto', models.CharField(max_length=25, verbose_name='Identificación')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('eval', models.BooleanField(default=True, verbose_name='Evaluación')),
                ('ciclos', models.PositiveSmallIntegerField(verbose_name='Repeticiones')),
                ('description', models.TextField(verbose_name='Descripción de la Meta')),
                ('soporte', models.FileField(blank=True, null=True, upload_to=metas.models.archivo_soporte, verbose_name='Soporte')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='meta_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Control de Metas del SPE',
            },
        ),
    ]
