# Generated by Django 2.0.5 on 2018-05-23 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import metas.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JMM01',
            fields=[
                ('fecha', models.DateField()),
                ('eval_calidad', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Evaluación del Criterio de Calidad')),
                ('eval_oportunidad', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Evaluación del Criterio de Oportunidad')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporte', models.FileField(upload_to=metas.models.subir_archivo, verbose_name='Reporte')),
                ('oficio', models.FileField(upload_to=metas.models.subir_archivo, verbose_name='Oficio/correo JMM a VR')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidenciaFK_meta', to='metas.MetasSPE')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidenciaFK_pipol', to=settings.AUTH_USER_MODEL, verbose_name='Miembro del SPE')),
                ('usuario', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='evidenciaFK_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
