# Generated by Django 2.0.5 on 2018-05-23 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0002_jmm01'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jmm01',
            options={'verbose_name': 'Evidencia JMM01', 'verbose_name_plural': 'Evidencias para la meta JMM01'},
        ),
    ]
