# Generated by Django 2.0.5 on 2018-05-24 00:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0005_auto_20180523_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='metasspe',
            name='campos',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
