# Generated by Django 2.0.5 on 2018-06-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20180606_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['tipo', 'id']},
        ),
    ]
