# Generated by Django 5.0.6 on 2024-08-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='fuente',
            field=models.IntegerField(blank=True, choices=[(1, 'Auditoría Externa'), (2, 'Auditoría Interna'), (3, 'Queja del cliente'), (4, 'Revisión por la Dirección'), (5, 'Proceso'), (6, 'Documentación del SGC'), (7, 'Objetivos e Indicadores'), (8, 'Evaluación de riesgos'), (9, 'Otros')], null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='proceso',
            field=models.IntegerField(blank=True, choices=[(1, 'Estratégico'), (2, 'Sustantivos'), (3, 'Soporte'), (4, 'Medición, Análisis y Mejora'), (5, 'SGC')], null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Corrección'), (2, 'Acción Correctiva'), (3, 'Riesgo')], help_text='Tipo de acción requerida', null=True),
        ),
    ]
