# Generated by Django 5.0.6 on 2024-08-29 20:57

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0002_alter_plan_fuente_alter_plan_proceso_alter_plan_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='fecha_deteccion',
        ),
        migrations.AddField(
            model_name='plan',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='desc_cnc',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Descripción de la No Conformidad / Riesgo'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='documento',
            field=models.IntegerField(choices=[(1, 'Cédula de No Conformidad'), (2, 'Plan de Cambios y Mejoras al SGC')], help_text='Selecciona el tipo de plan', verbose_name='Tipo de plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='otra_fuente',
            field=models.TextField(blank=True, help_text='Especifique la fuente si seleccionó Otros', null=True, verbose_name='Otra (especifique)'),
        ),
    ]
