# Generated by Django 5.0.6 on 2024-09-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0004_alter_plan_consecuencias_alter_plan_desc_pcm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accion',
            name='responsable',
            field=models.TextField(blank=True, help_text='Iniciales del Responsable', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='proposito',
            field=models.CharField(blank=True, help_text='Propósito del cambio o mejora al SGC', max_length=255, null=True, verbose_name='Propósito'),
        ),
    ]
