# Generated by Django 5.0.6 on 2024-09-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0006_alter_accion_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='responsable',
            field=models.CharField(blank=True, help_text='Iniciales del Responsable', max_length=5, null=True),
        ),
    ]
