# Generated by Django 5.0.6 on 2024-09-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0007_alter_seguimiento_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='accion',
            name='evidencia',
            field=models.CharField(blank=True, help_text='Evidencia documental esperada', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='fecha',
            field=models.DateField(help_text='Fecha de la actualización'),
        ),
    ]
