# Generated by Django 5.0.6 on 2024-09-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0009_alter_accion_recursos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accion',
            name='responsable',
            field=models.CharField(blank=True, help_text='Iniciales del Responsable', max_length=255, null=True),
        ),
    ]
