# Generated by Django 5.0.6 on 2025-11-06 14:21
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0010_alter_accion_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='responsable',
            field=models.CharField(
                blank=True,
                help_text='Persona responsable de la actualización',
                max_length=255,
                null=True,
            ),
        ),
    ]
