# Generated by Django 2.0.5 on 2018-05-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientedpi',
            name='distrito',
            field=models.PositiveSmallIntegerField(editable=False, help_text='Distrito'),
        ),
        migrations.AlterField(
            model_name='expedientedpi',
            name='entidad',
            field=models.PositiveSmallIntegerField(editable=False, help_text='Entidad'),
        ),
    ]
