# Generated by Django 2.1 on 2018-09-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientedpi',
            name='delta_verificar',
            field=models.SmallIntegerField(editable=False, help_text='Delta entre solicitud de verificación            y ejecución de la cédula', null=True),
        ),
    ]
