# Generated by Django 2.1 on 2018-09-04 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0002_auto_20180901_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedientedpi',
            name='completo',
        ),
        migrations.RemoveField(
            model_name='expedientedpi',
            name='delta_aclarar',
        ),
        migrations.RemoveField(
            model_name='expedientedpi',
            name='delta_distrito',
        ),
        migrations.RemoveField(
            model_name='expedientedpi',
            name='delta_entrevista',
        ),
        migrations.RemoveField(
            model_name='expedientedpi',
            name='delta_enviar',
        ),
        migrations.RemoveField(
            model_name='expedientedpi',
            name='delta_notificar',
        ),
        migrations.RemoveField(
            model_name='expedientedpi',
            name='delta_verificar',
        ),
        migrations.RemoveField(
            model_name='expedientedpi',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='expedientedpi',
            name='fecha_ejecucion_cedula',
        ),
        migrations.RemoveField(
            model_name='expedientedpi',
            name='fecha_entrevista',
        ),
        migrations.RemoveField(
            model_name='expedientedpi',
            name='fecha_entrevista_registro',
        ),
        migrations.RemoveField(
            model_name='expedientedpi',
            name='fecha_envio_expediente',
        ),
        migrations.RemoveField(
            model_name='expedientedpi',
            name='fecha_envio_expediente_registro',
        ),
        migrations.RemoveField(
            model_name='expedientedpi',
            name='fecha_notificacion_aclaracion',
        ),
        migrations.RemoveField(
            model_name='expedientedpi',
            name='fecha_notificacion_exclusion',
        ),
        migrations.RemoveField(
            model_name='expedientedpi',
            name='fecha_notificacion_rechazo',
        ),
        migrations.RemoveField(
            model_name='expedientedpi',
            name='fecha_notificacion_registro',
        ),
        migrations.RemoveField(
            model_name='expedientedpi',
            name='fecha_solicitud_cedula',
        ),
        migrations.RemoveField(
            model_name='expedientedpi',
            name='fecha_validacion_expediente',
        ),
        migrations.AddField(
            model_name='expedientedpi',
            name='atencion',
            field=models.DateField(default=datetime.date(2018, 9, 4), help_text='Pendiente de atención en la Vocalía Local'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expedientedpi',
            name='captura',
            field=models.DateField(default=datetime.date(2018, 9, 4), help_text='Situación en proceso de captura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expedientedpi',
            name='delta_proceso',
            field=models.SmallIntegerField(editable=False, help_text='Control de proceso', null=True),
        ),
        migrations.AddField(
            model_name='expedientedpi',
            name='resolucion',
            field=models.DateField(default=datetime.date(2018, 9, 4), help_text='Pendiente de resolución en análisis registral'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expedientedpi',
            name='tratamiento',
            field=models.DateField(default=datetime.date(2018, 9, 4), help_text='Enviado a tratamiento de análisis registral'),
            preserve_default=False,
        ),
    ]
