# Generated by Django 2.0.5 on 2018-06-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0005_auto_20180528_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientedpi',
            name='fecha_entrevista_registro',
            field=models.DateField(blank=True, help_text='Fecha de la entrevista o Acta Administrativa', null=True, verbose_name='REGISTRO: Entrevista/Acta'),
        ),
        migrations.AddField(
            model_name='expedientedpi',
            name='fecha_envio_expediente_registro',
            field=models.DateField(blank=True, help_text='REGISTRO: Fecha de envío de expediente a la JL', null=True, verbose_name='REGISTRO: Envio a JL'),
        ),
        migrations.AddField(
            model_name='expedientedpi',
            name='fecha_notificacion_registro',
            field=models.DateField(blank=True, help_text='Fecha de notificación de aclaración al ciudadano AC', null=True, verbose_name='REGISTRO: Notificación'),
        ),
        migrations.AlterField(
            model_name='expedientedpi',
            name='fecha_entrevista',
            field=models.DateField(blank=True, help_text='TRÁMITE: Fecha de la entrevista o Acta Administrativa', null=True),
        ),
        migrations.AlterField(
            model_name='expedientedpi',
            name='fecha_envio_expediente',
            field=models.DateField(blank=True, help_text='TRÁMITE: Fecha de envío de expediente a la JL', null=True),
        ),
        migrations.AlterField(
            model_name='expedientedpi',
            name='fecha_notificacion_aclaracion',
            field=models.DateField(blank=True, help_text='Fecha de notificación de aclaración al ciudadano AC', null=True, verbose_name='TRÁMITE: Notificación'),
        ),
    ]
