# Generated by Django 2.0.5 on 2018-06-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0008_auto_20180618_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientedpi',
            name='completo',
            field=models.BooleanField(),
        ),
    ]
