# Generated by Django 2.0.5 on 2018-05-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0003_auto_20180528_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientedpi',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No indica'), (1, 'Rechazado'), (2, 'Error en MAC'), (3, 'Aclarado')], help_text='Estado del trámite'),
        ),
        migrations.AlterField(
            model_name='expedientedpi',
            name='fecha_notificacion_aclaracion',
            field=models.DateField(blank=True, help_text='Fecha de notificación de aclaración al ciudadano AC', null=True, verbose_name='Notificación'),
        ),
    ]
