# Generated by Django 2.0.5 on 2018-06-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0006_auto_20180601_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientedpi',
            name='completo',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
