# Generated by Django 2.0.5 on 2018-06-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0007_expedientedpi_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientedpi',
            name='completo',
            field=models.BooleanField(default=False),
        ),
    ]
