# Generated by Django 2.0.5 on 2018-06-18 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0009_auto_20180618_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedientedpi',
            name='completo',
        ),
    ]
