# Generated by Django 2.1 on 2018-08-24 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('fecha_corte', models.DateField(editable=False, null=True, verbose_name='Fecha de Corte')),
                ('distrito', models.CharField(choices=[('1', 'Apizaco - Distrito 01'), ('2', 'Tlaxcala - Distrito 02'), ('3', 'Zacatelco - Distrito 03')], max_length=1, verbose_name='Distrito')),
                ('lote', models.CharField(max_length=11)),
                ('tipo_lote', models.CharField(choices=[('ORD', 'ORD'), ('BIS', 'BIS'), ('REI', 'REI'), ('RA', 'RA'), ('EXT', 'EXT')], max_length=3, verbose_name='Tipo de Lote')),
                ('num_prod', models.CharField(max_length=7, verbose_name='Número de Producción')),
                ('tipo_cinta', models.CharField(choices=[('1', 'Actualizaciones'), ('2', 'Recurso de Apelación')], max_length=1, verbose_name='Tipo de Cinta')),
                ('modulos', models.PositiveSmallIntegerField(verbose_name='Número de Módulos')),
                ('credenciales', models.IntegerField(verbose_name='Número de FCPVF en el envio')),
                ('cajas', models.PositiveSmallIntegerField(verbose_name='Número de cajas')),
                ('envio_cnd', models.DateTimeField(verbose_name='Fecha de envio CND')),
                ('recibido_vrd', models.DateTimeField(verbose_name='Fecha de recibido en Vocalía Distrital')),
                ('transito', models.DurationField(editable=False)),
                ('tran_sec', models.FloatField(editable=False)),
                ('autor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='prod_parcel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
            },
        ),
        migrations.CreateModel(
            name='EnvioModulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(choices=[('151', '290151'), ('152', '290152'), ('153', '290153'), ('154', '290154'), ('251', '290251'), ('252', '290252'), ('253', '290253'), ('254', '290254'), ('351', '290351'), ('352', '290352'), ('353', '290353')], max_length=3)),
                ('paquetes', models.PositiveSmallIntegerField()),
                ('formatos', models.IntegerField()),
                ('recibido_mac', models.DateTimeField()),
                ('disponible_mac', models.DateTimeField()),
                ('transito', models.DurationField(editable=False)),
                ('tran_sec', models.FloatField(editable=False)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paquetes.Envio')),
            ],
            options={
                'verbose_name': 'Paquete',
                'verbose_name_plural': 'Paquetes a MAC',
            },
        ),
        migrations.AlterUniqueTogether(
            name='enviomodulo',
            unique_together={('lote', 'mac')},
        ),
        migrations.AlterUniqueTogether(
            name='envio',
            unique_together={('lote', 'distrito', 'recibido_vrd')},
        ),
    ]
