# Generated by Django 2.1 on 2018-08-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envio',
            old_name='creado',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='envio',
            old_name='modificado',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='envio',
            name='distrito',
            field=models.CharField(choices=[(1, 'Apizaco - Distrito 01'), (2, 'Tlaxcala - Distrito 02'), (3, 'Zacatelco - Distrito 03')], max_length=1, verbose_name='Distrito'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='tipo_cinta',
            field=models.CharField(choices=[(1, 'Actualizaciones'), (2, 'Recurso de Apelación')], max_length=1, verbose_name='Tipo de Cinta'),
        ),
    ]
