# Generated by Django 2.1 on 2018-08-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0002_auto_20180824_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='distrito',
            field=models.CharField(choices=[('1', 'Apizaco - Distrito 01'), ('2', 'Tlaxcala - Distrito 02'), ('3', 'Zacatelco - Distrito 03')], max_length=1, verbose_name='Distrito'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='tipo_cinta',
            field=models.CharField(choices=[('1', 'Actualizaciones'), ('2', 'Recurso de Apelación')], max_length=1, verbose_name='Tipo de Cinta'),
        ),
        migrations.AlterField(
            model_name='enviomodulo',
            name='mac',
            field=models.CharField(choices=[('151', '290151'), ('152', '290152'), ('153', '290153'), ('154', '290154'), ('251', '290251'), ('252', '290252'), ('253', '290253'), ('254', '290254'), ('291', '290291'), ('351', '290351'), ('352', '290352'), ('353', '290353')], max_length=3),
        ),
    ]
