# Generated by Django 2.1 on 2018-08-10 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cifras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tramites', models.IntegerField()),
                ('cred_recibidas', models.IntegerField(verbose_name='Credenciales recibidas')),
                ('cred_entregadas', models.IntegerField(verbose_name='Credenciales entregadas')),
                ('atenciones', models.IntegerField(editable=False)),
                ('prod_dia', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('prod_dia_est', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('dias_trabajados', models.PositiveSmallIntegerField(verbose_name='Días trabajados')),
                ('jornada', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Jornada Trabajada')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cifras_semanales', to='core.Modulo')),
            ],
            options={
                'verbose_name': 'Cifras Semanales',
                'verbose_name_plural': 'Reportes de Cifras',
                'ordering': ['modulo__distrito', 'modulo__modulo'],
            },
        ),
        migrations.CreateModel(
            name='ReporteSemanal',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_corte', models.DateField(verbose_name='Fecha de Corte')),
                ('remesa', models.CharField(max_length=7, unique=True, verbose_name='Remesa')),
                ('notas', models.TextField(verbose_name='Observaciones')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='productividad_remesa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Productividad',
                'verbose_name_plural': 'Reportes de Productividad',
                'ordering': ['-fecha_corte'],
                'get_latest_by': 'fecha_corte',
            },
        ),
        migrations.AddField(
            model_name='cifras',
            name='reporte_semanal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cifras_reporte_semanal', to='productividad.ReporteSemanal'),
        ),
        migrations.AddField(
            model_name='cifras',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='productividad_cifras', to=settings.AUTH_USER_MODEL),
        ),
    ]
