# Generated by Django 2.1 on 2018-08-27 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cifras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.CharField(max_length=2, verbose_name='Distrito')),
                ('modulo', models.CharField(max_length=6, verbose_name='Módulo')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo de módulo')),
                ('dias_trabajados', models.PositiveSmallIntegerField(verbose_name='Días trabajados')),
                ('jornada_trabajada', models.FloatField(verbose_name='Jornada trabajada')),
                ('configuracion', models.CharField(max_length=10, verbose_name='Configuración')),
                ('tramites', models.SmallIntegerField(verbose_name='Trámites')),
                ('credenciales_entregadas_actualizacion', models.SmallIntegerField(help_text='Credenciales entregadas producto de trámites de actualización', verbose_name='Credenciales entregas')),
                ('credenciales_reimpresion', models.SmallIntegerField(help_text='Credenciales entregadas productos de solicitudes de reimpresión', verbose_name='Credenciales reimpresión')),
                ('total_atenciones', models.SmallIntegerField(verbose_name='Total de atención')),
                ('productividad_x_dia', models.SmallIntegerField(verbose_name='Productividad por día')),
                ('productividad_x_dia_x_estacion', models.SmallIntegerField(verbose_name='Productividad por día por estación')),
                ('credenciales_recibidas', models.SmallIntegerField(verbose_name='Credenciales recibidas')),
            ],
            options={
                'verbose_name': 'Cifras por módulo',
                'verbose_name_plural': 'Reportes de productividad',
                'ordering': ['distrito', 'modulo'],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fecha_corte', models.DateField(verbose_name='Fecha de Corte')),
                ('remesa', models.CharField(max_length=8, unique=True, verbose_name='Remesa')),
                ('notas', models.TextField(verbose_name='Observaciones')),
                ('archivo', models.FileField(upload_to='productividad', verbose_name='Archivo de cifras')),
                ('usuario', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='cifras_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Productividad',
                'verbose_name_plural': 'Reportes de Productividad',
                'ordering': ['-fecha_corte'],
                'get_latest_by': 'fecha_corte',
            },
        ),
        migrations.AddField(
            model_name='cifras',
            name='reporte_semanal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporte_cifras', to='productividad.Reporte'),
        ),
    ]
