# Generated by Django 2.0.5 on 2018-07-16 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productividad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cifras',
            options={'ordering': ['modulo__distrito', 'modulo__modulo'], 'verbose_name': 'Cifras Semanales', 'verbose_name_plural': 'Reportes de Cifras'},
        ),
        migrations.AlterField(
            model_name='cifras',
            name='reporte_semanal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cifras_reporte_semanal', to='productividad.ReporteSemanal'),
        ),
    ]
