# Generated by Django 2.1 on 2018-08-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productividad', '0002_auto_20180827_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpronosticotramites',
            name='tramites',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pronosticotramites',
            name='tramites',
            field=models.IntegerField(),
        ),
    ]
