# Generated by Django 2.1 on 2018-08-28 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productividad', '0003_auto_20180827_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpronosticotramites',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Pronóstico'},
        ),
        migrations.AlterModelOptions(
            name='pronosticotramites',
            options={'ordering': ('year', 'distrito'), 'verbose_name': 'Pronóstico', 'verbose_name_plural': 'Pronósticos de trámites'},
        ),
        migrations.AlterUniqueTogether(
            name='pronosticotramites',
            unique_together={('year', 'distrito')},
        ),
    ]
