# Generated by Django 2.1 on 2018-09-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productividad', '0004_auto_20180827_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporte',
            options={'get_latest_by': 'fecha_corte', 'ordering': ['-remesa'], 'verbose_name': 'Reporte de Productividad', 'verbose_name_plural': 'Reportes de Productividad'},
        ),
    ]
