# Generated by Django 2.2.1 on 2019-06-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productividad', '0006_auto_20190213_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='archivo',
            field=models.FileField(max_length=500, upload_to='productividad', verbose_name='Archivo de cifras'),
        ),
    ]
