# Generated by Django 3.2.5 on 2021-07-24 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productividad', '0007_auto_20190613_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.CharField(max_length=2, verbose_name='Distrito')),
                ('mac', models.CharField(max_length=6, verbose_name='Módulo')),
                ('type', models.CharField(max_length=20, verbose_name='Tipo de módulo')),
                ('days_worked', models.PositiveSmallIntegerField(verbose_name='Días trabajados')),
                ('hours_worked', models.FloatField(verbose_name='Jornada trabajada')),
                ('setup', models.CharField(max_length=10, verbose_name='Configuración')),
                ('tramites_aplicados', models.SmallIntegerField(verbose_name='Trámites')),
                ('cards_by_update', models.SmallIntegerField(help_text='Credenciales entregadas producto de trámites de actualización', verbose_name='Credenciales entregadas')),
                ('total_atenciones', models.SmallIntegerField(verbose_name='Total de atención')),
                ('numbers_by_day', models.SmallIntegerField(verbose_name='Productividad por día')),
                ('numbers_by_machine_by_day', models.SmallIntegerField(verbose_name='Productividad por día por estación')),
                ('credenciales_recibidas', models.SmallIntegerField(verbose_name='Credenciales recibidas')),
                ('reporte_semanal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporte_cifras', to='productividad.reporte')),
            ],
            options={
                'verbose_name': 'Cifras por módulo',
                'verbose_name_plural': 'Reportes de productividad',
                'ordering': ['distrito', 'mac'],
            },
        ),
        migrations.DeleteModel(
            name='Cifras',
        ),
    ]
