# Generated by Django 3.2.5 on 2021-07-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productividad', '0008_auto_20210723_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbers',
            name='days_worked',
            field=models.FloatField(verbose_name='Días trabajados'),
        ),
    ]
