# Generated by Django 5.0.6 on 2024-09-13 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(help_text='Posición u orden del KPI', verbose_name='Posición')),
                ('type', models.IntegerField(choices=[(1, 'KPO'), (2, 'KPI')], help_text='Indica si es una KPO o un KPI', verbose_name='Tipo')),
                ('name', models.CharField(help_text='Nombre del KPI o KPO', max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(help_text='Descripción detallada del KPI o KPO', verbose_name='Descripción')),
                ('period', models.IntegerField(choices=[('1', 'Semanal'), ('2', 'Remesa'), ('3', 'Mensual'), ('4', 'Bimestral'), ('5', 'Trimestral'), ('6', 'Cuatrimestral'), ('7', 'Semestral'), ('8', 'Anual'), ('99', 'Por campaña')], verbose_name='Periodo')),
                ('period_begin', models.DateField(verbose_name='Inicio')),
                ('period_end', models.DateField(verbose_name='Fin')),
                ('lapse', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Lapso')),
                ('formula', models.TextField(verbose_name='Fórmula')),
                ('target', models.FloatField(verbose_name='Meta')),
                ('nominal', models.FloatField(verbose_name='Nominativo')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
            },
        ),
    ]
