# Generated by Django 5.2.4 on 2025-07-08 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('CAP', 'Campaña Anual Permanente'), ('CAI', 'Campaña Anual Intensa')], max_length=3)),
                ('meta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('forecast', models.PositiveIntegerField()),
                ('acumulado', models.FloatField(default=0.0)),
            ],
            options={
                'unique_together': {('year', 'type')},
            },
        ),
        migrations.CreateModel(
            name='TramiteMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('tramites', models.PositiveIntegerField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.campaign')),
            ],
            options={
                'unique_together': {('campaign', 'year', 'month')},
            },
        ),
    ]
