# Generated by Django 5.0.6 on 2024-09-13 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('pos', models.IntegerField(help_text='Posición u orden del Indicador', verbose_name='Posición')),
                ('type', models.IntegerField(choices=[(1, 'Objetivo'), (2, 'Indicador')], help_text='Indica si es una Objetivo o un KPI', verbose_name='Tipo')),
                ('name', models.CharField(help_text='Nombre del Objetivo o Indicador', max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(help_text='Descripción detallada del Objetivo o Indicador', verbose_name='Descripción')),
                ('period', models.CharField(choices=[('1', 'Semanal'), ('2', 'Remesa'), ('3', 'Mensual'), ('4', 'Bimestral'), ('5', 'Trimestral'), ('6', 'Cuatrimestral'), ('7', 'Semestral'), ('8', 'Anual'), ('C', 'Por campaña'), ('R', 'Por campaña/remesa'), ('M', 'Por campaña/mensual'), ('S', 'Por campaña/semanal')], help_text='Periodo de medición del Indicador', max_length=1, verbose_name='Periodo')),
                ('period_begin', models.DateField(verbose_name='Inicio')),
                ('period_end', models.DateField(verbose_name='Fin')),
                ('lapse', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Lapso')),
                ('formula', models.TextField(verbose_name='Fórmula')),
                ('target', models.FloatField(verbose_name='Meta')),
                ('nominal', models.FloatField(verbose_name='Nominativo')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Fecha')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.kpi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'ordering': ('kpi', 'date'),
            },
        ),
    ]
