# Generated by Django 5.0.6 on 2024-09-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='description',
            field=models.TextField(help_text='Descripción detallada del Objetivo o Indicador', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='name',
            field=models.CharField(help_text='Nombre del Objetivo o Indicador', max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='pos',
            field=models.IntegerField(help_text='Posición u orden del Indicador', verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='type',
            field=models.IntegerField(choices=[(1, 'Objetivo'), (2, 'Indicador')], help_text='Indica si es una Objetivo o un KPI', verbose_name='Tipo'),
        ),
    ]
