# Generated by Django 5.2.4 on 2025-07-08 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0002_alter_campaign_options_alter_tramitemensual_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tramitemensual',
            unique_together={('campaign', 'month')},
        ),
        migrations.RemoveField(
            model_name='tramitemensual',
            name='year',
        ),
    ]
