# Generated by Django 5.0.6 on 2024-09-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0002_alter_kpi_description_alter_kpi_name_alter_kpi_pos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='period',
            field=models.CharField(choices=[('1', 'Semanal'), ('2', 'Remesa'), ('3', 'Mensual'), ('4', 'Bimestral'), ('5', 'Trimestral'), ('6', 'Cuatrimestral'), ('7', 'Semestral'), ('8', 'Anual'), ('C', 'Por campaña')], help_text='Periodo de medición del Indicador', max_length=1, verbose_name='Periodo'),
        ),
    ]
