# Generated by Django 5.0.6 on 2024-09-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0002_alter_record_options_remove_kpi_lapse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='lapse',
            field=models.IntegerField(choices=[(1, 'Semanal'), (1, 'Remesa'), (3, 'Mensual'), (4, 'Bimestral'), (5, 'Trimestral'), (6, 'Cuatrimestral'), (7, 'Semestral'), (8, 'Anual'), (9, 'Por campaña'), (10, 'Por campaña/remesa'), (11, 'Por campaña/mensual'), (12, 'Por campaña/semanal')], default=3, help_text='Periodo de medición', verbose_name='Medición'),
        ),
    ]
