# Generated by Django 5.2.4 on 2025-07-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0003_alter_tramitemensual_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='avance',
            field=models.FloatField(default=0.0, editable=False, help_text='Porcentaje de avance de la campaña'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='acumulado',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Número de trámites acumulados hasta la fecha', verbose_name='Trámites acumulados'),
        ),
    ]
