# Generated by Django 5.0.6 on 2024-09-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0003_kpi_lapse'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='cumulative_value',
            field=models.FloatField(default=0, verbose_name='Valor Acumulado'),
        ),
    ]
