# Generated by Django 5.0.6 on 2024-09-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0004_record_cumulative_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='cumulative_percentage',
            field=models.FloatField(default=0, verbose_name='Porcentaje Acumulado'),
        ),
        migrations.AddField(
            model_name='record',
            name='percentage_of_nominal',
            field=models.FloatField(default=0, verbose_name='Porcentaje del Nominal'),
        ),
    ]
