# Generated by Django 5.0.6 on 2024-09-13 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0004_alter_kpi_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='period',
            field=models.CharField(choices=[('1', 'Semanal'), ('2', 'Remesa'), ('3', 'Mensual'), ('4', 'Bimestral'), ('5', 'Trimestral'), ('6', 'Cuatrimestral'), ('7', 'Semestral'), ('8', 'Anual'), ('C', 'Por campaña'), ('R', 'Por campaña/remesa'), ('M', 'Por campaña/mensual'), ('S', 'Por campaña/semanal')], help_text='Periodo de medición del Indicador', max_length=1, verbose_name='Periodo'),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.kpi')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'ordering': ('kpi', 'date'),
            },
        ),
    ]
