# Generated by Django 5.2.4 on 2025-07-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0004_campaign_avance_alter_campaign_acumulado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='meta',
        ),
        migrations.AddField(
            model_name='campaign',
            name='goal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Meta'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='type',
            field=models.CharField(choices=[('CAP', 'Campaña Anual Permanente'), ('CAI', 'Campaña Anual Intensa')], max_length=3, verbose_name='Tipo de Campaña'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Año'),
        ),
    ]
