# Generated by Django 5.2.4 on 2025-07-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0005_remove_campaign_meta_campaign_goal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'verbose_name': 'Trámites por Campaña', 'verbose_name_plural': 'Campañas'},
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='type',
            new_name='campaign_type',
        ),
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together={('year', 'campaign_type')},
        ),
    ]
