# Generated by Django 5.1.2 on 2024-10-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0006_kpi_chart_type_kpi_xaxis_label_kpi_xaxis_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='cumulative_percentage',
            field=models.FloatField(default=0, editable=False, verbose_name='Porcentaje Acumulado'),
        ),
        migrations.AlterField(
            model_name='record',
            name='cumulative_value',
            field=models.FloatField(default=0, editable=False, verbose_name='Valor Acumulado'),
        ),
        migrations.AlterField(
            model_name='record',
            name='percentage_of_nominal',
            field=models.FloatField(default=0, editable=False, verbose_name='Porcentaje del Nominal'),
        ),
    ]
