# Generated by Django 2.1 on 2018-08-10 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialModulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'Fijo Distrital'), (2, 'Fijo Adicional'), (3, 'Semifijo'), (4, 'Móvil'), (5, 'Urbano Itinerante')], verbose_name='Tipo de Módulo')),
                ('estaciones', models.PositiveSmallIntegerField(choices=[(1, 'Básico'), (2, 'Básico + 1'), (3, 'Básico + 2'), (4, 'Básico + 3'), (5, 'Básico + 4'), (6, 'Básico + 5')], verbose_name='Estaciones')),
                ('doble_turno', models.BooleanField(default=False, verbose_name='Doble Turno')),
                ('fecha_inicio', models.DateField(verbose_name='Inicio de operaciones')),
                ('fecha_termino', models.DateField(verbose_name='Fecha de término de operaciones')),
                ('horario', models.TextField(help_text='Escribe el horario del módulo')),
                ('observaciones', models.TextField(help_text='Describe brevemente la razón del cambio')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
                'get_latest_by': 'fecha_inicio',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('distrito', models.PositiveSmallIntegerField()),
                ('modulo', models.CharField(help_text='Clave completa del MAC a 6 dígitos', max_length=6, verbose_name='Módulo')),
            ],
        ),
        migrations.CreateModel(
            name='Remesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remesa', models.CharField(max_length=7)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='modulo',
            unique_together={('distrito', 'modulo')},
        ),
        migrations.AddField(
            model_name='historialmodulo',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historialmodulo', to='core.Modulo'),
        ),
        migrations.AddField(
            model_name='historialmodulo',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='historialMAC_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
