# Generated by Django 2.1 on 2018-09-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecyrd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramites',
            name='distrito',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tramites',
            name='mac',
            field=models.CharField(default='290101', max_length=6),
            preserve_default=False,
        ),
    ]
