# Generated by Django 2.1 on 2018-09-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecyrd', '0003_auto_20180901_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramites',
            name='tramo_disponible',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='tramites',
            name='tramo_entrega',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='tramites',
            name='tramo_exitoso',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
    ]
