# Generated by Django 2.2.1 on 2019-06-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprobacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(choices=[('290151', '290151'), ('290152', '290152'), ('290153', '290153'), ('290251', '290251'), ('290252', '290252'), ('290253', '290253'), ('290254', '290254'), ('290351', '290351'), ('290352', '290352'), ('290353', '290353')], max_length=6, verbose_name='Módulo')),
                ('distrito', models.PositiveSmallIntegerField(editable=False, verbose_name='Distrito')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('calificacion', models.FloatField(verbose_name='Calificación')),
                ('nota', models.TextField()),
            ],
        ),
    ]
