# Generated by Django 2.2.1 on 2019-06-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprobacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprobacion',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
    ]
