# Generated by Django 2.2.1 on 2019-06-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprobacion', '0002_auto_20190610_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprobacion',
            name='mac',
            field=models.CharField(choices=[('290151', '290151'), ('290152', '290152'), ('290153', '290153'), ('290154', '290154'), ('290251', '290251'), ('290253', '290253'), ('290254', '290254'), ('290351', '290351'), ('290352', '290352'), ('290353', '290353')], max_length=6, verbose_name='Módulo'),
        ),
    ]
